import { useEffect, useState } from 'react'
import { Link } from '../lib/router'
import { useRouter } from '../lib/RouterContext'
import { api, useResource } from '../lib/api'
import Brand from '../components/Brand'
import ResourceState from '../components/ResourceState'
import Icon from '../components/Icon'
import '../styles/admin.css'

const date = value => new Date(value).toLocaleString(undefined,{dateStyle:'medium',timeStyle:'short'})
const blankProject={title:'',description:'',link:'',category:'Web platforms',published:true,featured:false,order:0}
function Alert({children,success=false}) { return children?<p className={`admin-alert ${success?'admin-alert-success':''}`} role={success?'status':'alert'}>{children}</p>:null }
function Pagination({page,pages,total,onChange}) { return <div className="admin-pagination"><span>{total} total · Page {page} of {pages}</span><div><button disabled={page<=1} onClick={()=>onChange(page-1)}>← Previous</button><button disabled={page>=pages} onClick={()=>onChange(page+1)}>Next →</button></div></div> }

function Login({onLogin,notice}) {
  const [username,setUsername]=useState(''),[password,setPassword]=useState(''),[error,setError]=useState(''),[busy,setBusy]=useState(false)
  async function submit(event) { event.preventDefault();setBusy(true);setError('');try {const result=await api('/api/admin/login',{method:'POST',body:JSON.stringify({username,password})});onLogin(result)} catch(err){setError(err.message)} finally{setBusy(false)} }
  return <div className="admin-login"><div className="admin-login-card"><Brand/><span className="admin-kicker">SMARTAXIS / CONTENT STUDIO</span><h1>Welcome back.</h1><p>Manage your work. Stay close to your next opportunity.</p><Alert>{notice}</Alert><form onSubmit={submit}><label>Username<input autoComplete="username" value={username} onChange={e=>setUsername(e.target.value)} required autoFocus/></label><label>Password<input type="password" autoComplete="current-password" value={password} onChange={e=>setPassword(e.target.value)} required maxLength={256}/></label><Alert>{error}</Alert><button className="admin-primary" disabled={busy}>{busy?'Signing in…':'Sign in to your workspace'}<Icon name="arrow" size={18}/></button></form><Link to="/" className="admin-back">← Back to website</Link></div><p className="admin-login-note">A private workspace for your projects and conversations.</p></div>
}

function Overview() {
  const resource=useResource('/api/admin/overview'),stats=resource.data
  return <><div className="admin-heading"><div><span className="admin-kicker">YOUR WORKSPACE AT A GLANCE</span><h1>Good to see you.</h1><p>Keep your portfolio current and your conversations moving.</p></div><Link to="/admin/projects" className="admin-primary">Manage projects <Icon name="diagonal" size={18}/></Link></div><ResourceState {...resource}>{stats&&<><div className="admin-stats">{[['Total projects',stats.projects,'design'],['Published projects',stats.published,'globe'],['Total inquiries',stats.inquiries,'nodes'],['New inquiries',stats.unread,'bolt']].map(([label,value,icon])=><article key={label}><div><span>{label}</span><Icon name={icon} size={20}/></div><strong>{value}</strong><small>{label==='New inquiries'?'Waiting for your attention':'Live from your workspace'}</small></article>)}</div><div className="admin-quick-grid"><Link to="/admin/projects" className="admin-quick-card"><Icon name="design" size={30}/><h2>Put your work out there.</h2><p>Add a project with its image, story, and live link. Publish it when it is ready.</p><span>Open projects ↗</span></Link><Link to="/admin/inquiries" className="admin-quick-card"><Icon name="nodes" size={30}/><h2>Your next conversation.</h2><p>Read incoming inquiries, track follow-ups, and archive completed conversations.</p><span>Open inbox ↗</span></Link></div></>}</ResourceState></>
}

function ProjectEditor({project,onCancel,onSaved}) {
  const [values,setValues]=useState({...blankProject,...project}),[file,setFile]=useState(null),[error,setError]=useState(''),[busy,setBusy]=useState(false)
  const preview=file?.url||project?.image||''
  useEffect(()=>()=>{if(file)URL.revokeObjectURL(file.url)},[file])
  function update(event) {const {name,value,type,checked}=event.target;setValues(old=>({...old,[name]:type==='checkbox'?checked:value}))}
  function imageChange(event) { const selected=event.target.files[0];setError('');if(!selected){setFile(null);return}if(selected.size>4*1024*1024||!['image/jpeg','image/png','image/webp'].includes(selected.type)){setError('Choose a JPG, PNG, or WebP image under 4 MB.');event.target.value='';setFile(null);return}setFile({value:selected,url:URL.createObjectURL(selected)}) }
  async function submit(event) {
    event.preventDefault();setBusy(true);setError('')
    const data=new FormData()
    for(const name of Object.keys(blankProject))data.append(name,String(values[name]))
    if(file)data.append('image',file.value)
    try {await api(project?.id?`/api/admin/projects/${project.id}`:'/api/admin/projects',{method:project?.id?'PUT':'POST',body:data});onSaved(project?.id?'Project updated.':'Project added.')}
    catch(err){setError(err.message)}finally{setBusy(false)}
  }
  return <section className="admin-editor"><div className="admin-section-title"><div><span className="admin-kicker">PROJECT DETAILS</span><h2>{project?.id?'Edit project':'Create a project'}</h2></div><button className="admin-quiet" onClick={onCancel} disabled={busy}>Cancel</button></div><form onSubmit={submit} className="admin-editor-form"><div className="admin-editor-fields"><label>Project title<input name="title" value={values.title} onChange={update} required minLength={2} maxLength={120} placeholder="Your project name"/></label><label>Description<textarea name="description" value={values.description} onChange={update} required minLength={10} maxLength={5000} rows={5} placeholder="Describe what you built and what makes it special."/></label><label>Live project URL<input type="url" name="link" value={values.link} onChange={update} required maxLength={2048} placeholder="https://your-project.com"/></label><div className="admin-form-row"><label>Category<select name="category" value={values.category} onChange={update}>{['Web platforms','E-commerce','Mobile apps','Design','Other'].map(value=><option key={value}>{value}</option>)}</select></label><label>Display order<input type="number" name="order" value={values.order} onChange={update} min="0" max="9999" step="1" required/><small>Lower numbers appear first.</small></label></div><div className="admin-checkboxes"><label><input type="checkbox" name="published" checked={values.published} onChange={update}/> Publish on website</label><label><input type="checkbox" name="featured" checked={values.featured} onChange={update}/> Feature on homepage</label></div></div><div className="admin-upload"><label htmlFor="project-image">Project image</label><div className="admin-image-preview">{preview?<img src={preview} alt="Project image preview"/>:<div><Icon name="design" size={38}/><span>Your work belongs here.</span></div>}</div><input id="project-image" type="file" accept="image/jpeg,image/png,image/webp" onChange={imageChange} required={!project?.image}/><p>Choose an image from your device. JPG, PNG, or WebP, up to 4 MB. A landscape image works best.</p>{project?.image&&<small>Keep the current image by leaving this field empty.</small>}</div><div className="admin-form-footer"><Alert>{error}</Alert><button className="admin-primary" disabled={busy}>{busy?'Saving project…':project?.id?'Save changes':'Create project'}<Icon name="check" size={18}/></button></div></form></section>
}

function Projects() {
  const [page,setPage]=useState(1),[search,setSearch]=useState(''),[query,setQuery]=useState(''),[editing,setEditing]=useState(null),[notice,setNotice]=useState(''),[error,setError]=useState(''),[deleting,setDeleting]=useState('')
  const resource=useResource(`/api/admin/projects?page=${page}&search=${encodeURIComponent(query)}`)
  async function remove(project) {if(!window.confirm(`Delete “${project.title}” and its image? This cannot be undone.`))return;setDeleting(project.id);setError('');try{await api(`/api/admin/projects/${project.id}`,{method:'DELETE'});setNotice('Project deleted.');if(resource.data.projects.length===1&&page>1)setPage(page-1);else resource.reload()}catch(err){setError(err.message)}finally{setDeleting('')}}
  return <><div className="admin-heading"><div><span className="admin-kicker">YOUR WORK, IN THE SPOTLIGHT</span><h1>Projects</h1><p>Create, refine, and publish your portfolio.</p></div><button className="admin-primary" onClick={()=>{setEditing({...blankProject});setNotice('')}} disabled={!!editing}>+ Add project</button></div><Alert success>{notice}</Alert><Alert>{error}</Alert>{editing&&<ProjectEditor key={editing.id||'new'} project={editing} onCancel={()=>setEditing(null)} onSaved={message=>{setEditing(null);setNotice(message);resource.reload()}}/>}<form className="admin-search" onSubmit={e=>{e.preventDefault();setQuery(search);setPage(1)}}><input aria-label="Search projects" value={search} onChange={e=>setSearch(e.target.value)} placeholder="Search by project title…" maxLength={100}/><button>Search</button>{query&&<button type="button" onClick={()=>{setSearch('');setQuery('');setPage(1)}}>Clear</button>}</form><ResourceState {...resource}>{resource.data&&<>{!resource.data.projects.length?<div className="admin-empty"><Icon name="design" size={40}/><h2>{query?'No matching projects.':'Your portfolio starts here.'}</h2><p>{query?'Try a different title.':'Add your first project with an image, description, and link.'}</p></div>:<div className="admin-project-grid">{resource.data.projects.map(project=><article className="admin-project-card" key={project.id}><img src={project.image} alt={project.title} loading="lazy"/><div className="admin-project-body"><div className="admin-project-meta"><span className={`admin-badge ${project.published?'badge-live':'badge-draft'}`}>{project.published?'Published':'Draft'}</span>{project.featured&&<span className="admin-badge">Featured</span>}</div><h2>{project.title}</h2><p>{project.description}</p><a href={project.link} target="_blank" rel="noopener noreferrer">Visit project ↗</a><div className="admin-card-actions"><button disabled={!!editing||!!deleting} onClick={()=>{setEditing(project);setNotice('');window.scrollTo({top:0,behavior:'smooth'})}}>Edit project</button><button className="admin-danger" disabled={!!deleting} onClick={()=>remove(project)}>{deleting===project.id?'Deleting…':'Delete'}</button></div></div></article>)}</div>}<Pagination page={page} pages={resource.data.pages} total={resource.data.total} onChange={setPage}/></>}</ResourceState></>
}

function Inquiries() {
  const [page,setPage]=useState(1),[status,setStatus]=useState(''),[selected,setSelected]=useState(null),[error,setError]=useState(''),[busy,setBusy]=useState(false)
  const resource=useResource(`/api/admin/inquiries?page=${page}&status=${status}`)
  async function changeStatus(value){setBusy(true);setError('');try{await api(`/api/admin/inquiries/${selected.id}`,{method:'PATCH',body:JSON.stringify({status:value})});setSelected({...selected,status:value});resource.reload()}catch(err){setError(err.message)}finally{setBusy(false)}}
  async function remove(){if(!window.confirm('Permanently delete this inquiry?'))return;setBusy(true);setError('');try{await api(`/api/admin/inquiries/${selected.id}`,{method:'DELETE'});setSelected(null);if(resource.data.inquiries.length===1&&page>1)setPage(page-1);else resource.reload()}catch(err){setError(err.message)}finally{setBusy(false)}}
  return <><div className="admin-heading"><div><span className="admin-kicker">CONVERSATIONS THAT MATTER</span><h1>Inquiries</h1><p>Every new possibility, in one place.</p></div><button onClick={()=>resource.reload()} className="admin-quiet">Refresh inbox</button></div><div className="admin-filters">{[['','All inquiries'],['new','New'],['read','Read'],['archived','Archived']].map(([value,label])=><button key={label} aria-pressed={status===value} onClick={()=>{setStatus(value);setPage(1);setSelected(null)}}>{label}</button>)}</div><Alert>{error}</Alert><div className={`admin-inbox ${selected?'has-selection':''}`}><div><ResourceState {...resource}>{resource.data&&<>{resource.data.inquiries.length?<div className="admin-inquiry-list">{resource.data.inquiries.map(inquiry=><button key={inquiry.id} className={selected?.id===inquiry.id?'is-selected':''} onClick={()=>setSelected(inquiry)}><div><strong>{inquiry.name}</strong><span className={`admin-badge badge-${inquiry.status}`}>{inquiry.status}</span></div><span>{inquiry.email}</span><p>{inquiry.details}</p><small>{date(inquiry.createdAt)}</small></button>)}</div>:<div className="admin-empty"><Icon name="nodes" size={40}/><h2>No inquiries here yet.</h2><p>Messages sent through Contact Us will appear in this inbox.</p></div>}<Pagination page={page} pages={resource.data.pages} total={resource.data.total} onChange={setPage}/></>}</ResourceState></div>{selected&&<article className="admin-inquiry-detail"><div className="admin-section-title"><span className={`admin-badge badge-${selected.status}`}>{selected.status}</span><button className="admin-quiet" onClick={()=>setSelected(null)}>Close</button></div><h2>{selected.name}</h2><a href={`mailto:${encodeURIComponent(selected.email)}`}>{selected.email}</a><time>{date(selected.createdAt)}</time><dl><div><dt>Company</dt><dd>{selected.company||'Not provided'}</dd></div><div><dt>Phone</dt><dd>{selected.phone||'Not provided'}</dd></div><div><dt>Budget</dt><dd>{selected.budget||'To discuss'}</dd></div><div><dt>Services</dt><dd>{selected.services.join(', ')||'Help me decide'}</dd></div></dl><h3>Project details</h3><p className="inquiry-message">{selected.details}</p><label>Inquiry status<select value={selected.status} disabled={busy} onChange={e=>changeStatus(e.target.value)}><option value="new">New</option><option value="read">Read</option><option value="archived">Archived</option></select></label><div className="admin-detail-actions"><a className="admin-primary" href={`mailto:${encodeURIComponent(selected.email)}?subject=${encodeURIComponent('Your SmartAxis project inquiry')}`}>Reply by email ↗</a><button className="admin-danger" disabled={busy} onClick={remove}>Delete inquiry</button></div></article>}</div></>
}

function Account({onChanged}) {
  const [currentPassword,setCurrent]=useState(''),[newPassword,setNew]=useState(''),[confirmation,setConfirmation]=useState(''),[error,setError]=useState(''),[busy,setBusy]=useState(false)
  async function submit(event){event.preventDefault();setError('');if(newPassword!==confirmation){setError('New passwords do not match.');return}setBusy(true);try{await api('/api/admin/password',{method:'POST',body:JSON.stringify({currentPassword,newPassword})});onChanged()}catch(err){setError(err.message)}finally{setBusy(false)}}
  return <><div className="admin-heading"><div><span className="admin-kicker">YOUR ACCOUNT</span><h1>Keep your workspace yours.</h1><p>Use a unique password with at least 12 characters.</p></div></div><form className="admin-account-form" onSubmit={submit}><label>Current password<input type="password" autoComplete="current-password" value={currentPassword} onChange={e=>setCurrent(e.target.value)} required/></label><label>New password<input type="password" autoComplete="new-password" value={newPassword} onChange={e=>setNew(e.target.value)} required minLength={12} maxLength={128}/></label><label>Confirm new password<input type="password" autoComplete="new-password" value={confirmation} onChange={e=>setConfirmation(e.target.value)} required minLength={12} maxLength={128}/></label><Alert>{error}</Alert><button className="admin-primary" disabled={busy}>{busy?'Updating password…':'Update password'}</button><p>After updating, sign in again with your new password. All existing sessions will end.</p></form></>
}

export default function Admin() {
  const {path,navigate}=useRouter()
  const [session,setSession]=useState(null),[checking,setChecking]=useState(true),[notice,setNotice]=useState('')
  const section=path==='/admin/projects'?'projects':path==='/admin/inquiries'?'inquiries':path==='/admin/account'?'account':'overview'
  useEffect(()=>{const controller=new AbortController();api('/api/admin/session',{signal:controller.signal}).then(setSession).catch(error=>{if(error.name!=='AbortError'&&error.status!==401)setNotice(error.message)}).finally(()=>{if(!controller.signal.aborted)setChecking(false)});return()=>controller.abort()},[])
  useEffect(()=>{const expired=()=>{setSession(null);setNotice('Your session has expired. Please sign in again.')};window.addEventListener('admin-session-expired',expired);return()=>window.removeEventListener('admin-session-expired',expired)},[])
  async function logout(){try{await api('/api/admin/logout',{method:'POST'});setSession(null);setNotice('');navigate('/admin')}catch(error){setNotice(error.message)}}
  if(checking)return <div className="admin-login"><p role="status">Opening your workspace…</p></div>
  if(!session)return <Login notice={notice} onLogin={user=>{setSession(user);setNotice('')}}/>
  return <div className="admin-app"><aside className="admin-sidebar"><Brand/><span className="admin-workspace-label">CONTENT STUDIO</span><nav aria-label="Admin navigation">{[['overview','Overview','/admin','nodes'],['projects','Projects','/admin/projects','design'],['inquiries','Inquiries','/admin/inquiries','globe'],['account','Account','/admin/account','shield']].map(([key,label,url,icon])=><Link key={key} to={url} aria-current={section===key?'page':undefined}><Icon name={icon} size={19}/>{label}</Link>)}</nav><div className="admin-sidebar-bottom"><Link to="/" target="_blank" rel="noopener noreferrer">View website <Icon name="diagonal" size={16}/></Link><span>Signed in as <strong>{session.username}</strong></span><button onClick={logout}>Sign out</button></div></aside><main className="admin-main"><Alert>{notice}</Alert>{section==='projects'?<Projects/>:section==='inquiries'?<Inquiries/>:section==='account'?<Account onChanged={()=>{setSession(null);setNotice('Password updated. Sign in with your new password.')}}/>:<Overview/>}</main></div>
}
