import { useState } from 'react'
import { Link } from '../lib/router'
import WorkShowcase from '../components/WorkShowcase'
import { Eyebrow, Button, CTA } from '../components/UI'
import HeroSculpture from '../components/HeroSculpture'

import Icon from '../components/Icon'

export default function Home() {
  const [motionPaused, setMotionPaused] = useState(false)
  return <>
    <section className="future-hero">
      <div className="hero-aurora" aria-hidden="true"/>
      <div className="container future-hero-layout">
        <div className="future-hero-copy"><div className="hero-badge"><span/> YOUR NEXT BIG THING STARTS HERE <Icon name="diagonal" size={13}/></div>
          <h1>Beyond ordinary.<br/><span>Built for</span><br/><span className="hero-gradient">what’s next.</span></h1>
          <p>Websites, mobile apps and custom software for businesses in India.<br className="desktop-break"/> From UI/UX design to launch, we turn your idea into a product people can use.</p>
          <div className="future-actions"><Button>Let’s build your next</Button><a href="#selected-work" className="hero-work-link"><span><Icon name="arrow" size={17}/></span>Explore the work</a></div>
          <div className="hero-mini-proof"><span className="mini-axis">✳</span><p>Design-led. Engineering-driven.<br/><strong>One team. Every possibility.</strong></p></div>
        </div>
        <div className="future-hero-art"><div className="art-cross cross-one">+</div><div className="art-cross cross-two">+</div><HeroSculpture paused={motionPaused}/><button className="art-motion-toggle" aria-label={motionPaused ? 'Play hero animation' : 'Pause hero animation'} aria-pressed={motionPaused} onClick={() => setMotionPaused(!motionPaused)}>{motionPaused ? '▷' : 'Ⅱ'}</button><div className="sculpture-tag tag-design"><span className="tag-icon"><Icon name="design" size={20}/></span><div><small>01 / IMAGINE</small><strong>Made to stand out.</strong></div></div><div className="sculpture-tag tag-engineer"><span className="tag-icon"><Icon name="code" size={20}/></span><div><small>02 / ENGINEER</small><strong>Built to go further.</strong></div><span className="tag-status"/></div><span className="art-caption-new">IDEAS IN MOTION <span>SA / EXPLORATION 001</span></span></div>
      </div>
      <div className="hero-baseline container"><span>STRATEGY × DESIGN × TECHNOLOGY</span><span className="baseline-center">AN INDEPENDENT DIGITAL STUDIO</span><a href="#selected-work">KEEP EXPLORING <span>↓</span></a></div>
    </section>
    <div className="technology-rail"><div className="container"><p>Good ideas.<br/><strong>Great foundations.</strong></p><span>React<span className="tech-symbol">✳</span></span><span className="tech-next">NEXT.js</span><span>node<span className="tech-green">⬡</span>js</span><span>Flutter <span className="tech-symbol">↗</span></span><span className="tech-figma"><i/>Figma</span></div></div>
    <section id="selected-work" className="section container future-work"><div className="section-heading"><div><Eyebrow>01 — SELECTED WORK</Eyebrow><h2>Different by design.<br/><span className="text-muted">Remarkable by nature.</span></h2></div><Link to="/portfolio" className="text-link">All our work <Icon name="diagonal" size={19}/></Link></div><WorkShowcase/><p className="demo-caption">BUILT WITH CARE. EXPLORE OUR LATEST PROJECTS.</p></section>
    <section className="future-services section"><div className="container"><div className="section-heading"><div><Eyebrow>02 — BUILT AROUND YOUR AMBITION</Eyebrow><h2>Big-picture thinking.<br/><span className="text-muted">Pixel-perfect doing.</span></h2></div><p>Everything your digital future needs.<br/>Connected. Considered. Crafted together.</p></div>
      <div className="service-bento">
        <Link to="/services/ui-ux-design" className="bento-card bento-design"><div className="bento-top"><span>01 / DESIGN</span><Icon name="diagonal" size={24}/></div><div className="design-playground" aria-hidden="true"><div className="design-cursor"><Icon name="diagonal" size={22}/> Make it exceptional.</div><div className="design-frame"><span className="frame-dot"/><span className="frame-dot"/><span className="frame-dot"/><span className="frame-dot"/><span className="design-type">Aa<span>.</span></span></div><div className="design-swatches"><i/><i/><i/><i/></div></div><div className="bento-copy"><h3>Looks incredible.<br/>Feels effortless.</h3><p>Brand experiences, product design, and interfaces that put people first.</p><span>UI / UX · DESIGN SYSTEMS · PROTOTYPING</span></div></Link>
        <Link to="/services/web-development" className="bento-card bento-development"><div className="bento-top"><span>02 / DEVELOPMENT</span><Icon name="diagonal" size={24}/></div><div className="code-playground" aria-hidden="true"><div className="code-window"><div><i/><i/><i/><span>your-next-big-thing.tsx</span></div><pre><span>const</span> possibility = {'{'}<br/>  vision: <em>'Extraordinary'</em>,<br/>  experience: <em>'Seamless'</em>,<br/>  builtTo: <em>'Go further'</em><br/>{'}'};<br/><br/><span>return</span> &lt;<b>YourNextChapter</b> /&gt;</pre><div className="code-ready"><span/> Ready for what’s next <Icon name="check" size={15}/></div></div></div><div className="bento-copy"><h3>Beautiful outside.<br/>Brilliant underneath.</h3><p>Fast websites and scalable platforms, engineered with care from the ground up.</p><span>WEBSITES · WEB APPS · SAAS PLATFORMS</span></div></Link>
        <Link to="/services/app-development" className="bento-card bento-mobile"><div className="bento-top"><span>03 / MOBILE</span><Icon name="diagonal" size={24}/></div><div className="bento-copy"><h3>Big possibilities.<br/>Pocket-sized.</h3><p>Intuitive apps that make your product part of everyday life.</p><span>IOS · ANDROID · CROSS-PLATFORM</span></div><div className="mini-phone" aria-hidden="true"><i/><div>9:41 <span>▰</span></div><span className="phone-greeting">YOUR NEXT CHAPTER</span><strong>Hello,<br/>possibility.</strong><div className="phone-orb">✳</div><div className="phone-action">Let’s go <span>↗</span></div></div></Link>
        <Link to="/services/automation" className="bento-card bento-automate"><div className="bento-top"><span>04 / CONNECT</span><Icon name="diagonal" size={24}/></div><div className="bento-copy"><h3>Less friction.<br/>More forward.</h3><p>Smart systems and integrations that give your business room to grow.</p><span>AUTOMATION · APIS · INTEGRATIONS</span></div><div className="connect-art" aria-hidden="true"><i/><i/><i/><span className="connect-core"><Icon name="nodes" size={30}/></span><span className="connect-node connect-node-one"><Icon name="cloud" size={20}/></span><span className="connect-node connect-node-two"><Icon name="bolt" size={20}/></span></div></Link>
      </div><div className="services-bottom"><p>A new idea. A complex challenge. A better way forward.</p><Link to="/services" className="text-link">Find your starting point <Icon name="diagonal" size={18}/></Link></div>
    </div></section>
    <section className="section container future-partner"><div className="partner-art"><span className="partner-art-label">CONNECTED THINKING. SHARED AMBITION.</span><div className="partner-orbit"><i/><i/><i/><div className="partner-symbol">a<span>↗</span></div><span className="partner-dot"/></div><div className="partner-art-foot"><span>SMALL TEAM.</span><span>EXPANSIVE THINKING.</span></div></div><div className="partner-copy"><Eyebrow>03 — YOUR PEOPLE FOR WHAT’S NEXT</Eyebrow><h2>More than a team.<br/><span className="text-muted">An unfair advantage.</span></h2><p>We’re designers who think like engineers. Engineers who care about design. And people who take your ambition personally.</p><div className="partner-points"><div><Icon name="check" size={18}/><span>Direct conversations. Clear direction.</span></div><div><Icon name="check" size={18}/><span>Thoughtful details. Meaningful decisions.</span></div><div><Icon name="check" size={18}/><span>Built together. Made to last.</span></div></div><Button to="/about" secondary>Meet your digital partner</Button></div></section>
    <section className="future-process section"><div className="container"><div className="section-heading"><div><Eyebrow>04 — FROM WHAT IF TO WHAT’S NEXT</Eyebrow><h2>Your vision. Our craft.<br/><span className="text-muted">A clear way forward.</span></h2></div><Link to="/process" className="text-link">Inside our process <Icon name="diagonal" size={19}/></Link></div><div className="future-process-grid">{[['Discover','Find the right questions. Define the opportunity. Make a plan that matters.'],['Design','Explore the possibilities. Shape the experience. Get every detail right.'],['Develop','Build with purpose. Test in the real world. Make the complex feel simple.'],['Deliver','Launch with confidence. Learn from real use. Keep moving forward.']].map(([title, description], index) => <article key={title}><div><span>0{index+1}</span><Icon name="diagonal" size={20}/></div><h3>{title}<span>.</span></h3><p>{description}</p></article>)}</div></div></section>
    <CTA/>
  </>
}
