import { useState } from 'react'
import { Link } from '../lib/router'
import WorkShowcase from '../components/WorkShowcase'
import { Eyebrow, Button, CTA } from '../components/UI'
import HeroSculpture from '../components/HeroSculpture'

import Icon from '../components/Icon'

export default function Home() {
  const [motionPaused, setMotionPaused] = useState(false)
  return <>
    <section className="future-hero">
      <div className="hero-aurora" aria-hidden="true"/>
      <div className="container future-hero-layout">
        <div className="future-hero-copy"><div className="hero-badge"><span/> LET’S GROW YOUR BUSINESS <Icon name="diagonal" size={13}/></div>
          <h1>Come online.<br/><span>Grow your</span><br/><span className="hero-gradient">business.</span></h1>
          <p>Websites, mobile apps and custom software for businesses in India.<br className="desktop-break"/> We help you reach more customers and make your daily work easier.</p>
          <div className="future-actions"><Button>Let’s talk</Button><a href="#selected-work" className="hero-work-link"><span><Icon name="arrow" size={17}/></span>See our products</a></div>
          <div className="hero-mini-proof"><span className="mini-axis">✳</span><p>Good design. Easy to use.<br/><strong>One team, from idea to launch.</strong></p></div>
        </div>
        <div className="future-hero-art"><div className="art-cross cross-one">+</div><div className="art-cross cross-two">+</div><HeroSculpture paused={motionPaused}/><button className="art-motion-toggle" aria-label={motionPaused ? 'Play hero animation' : 'Pause hero animation'} aria-pressed={motionPaused} onClick={() => setMotionPaused(!motionPaused)}>{motionPaused ? '▷' : 'Ⅱ'}</button><div className="sculpture-tag tag-design"><span className="tag-icon"><Icon name="design" size={20}/></span><div><small>01 / IMAGINE</small><strong>Made to stand out.</strong></div></div><div className="sculpture-tag tag-engineer"><span className="tag-icon"><Icon name="code" size={20}/></span><div><small>02 / ENGINEER</small><strong>Built to go further.</strong></div><span className="tag-status"/></div><span className="art-caption-new">IDEAS IN MOTION <span>SA / EXPLORATION 001</span></span></div>
      </div>
      <div className="hero-baseline container"><span>STRATEGY × DESIGN × TECHNOLOGY</span><span className="baseline-center">AN INDEPENDENT DIGITAL STUDIO</span><a href="#selected-work">KEEP EXPLORING <span>↓</span></a></div>
    </section>
    <div className="technology-rail"><div className="container"><p>Good ideas.<br/><strong>Great foundations.</strong></p><span>React<span className="tech-symbol">✳</span></span><span className="tech-next">NEXT.js</span><span>node<span className="tech-green">⬡</span>js</span><span>Flutter <span className="tech-symbol">↗</span></span><span className="tech-figma"><i/>Figma</span></div></div>
    <section id="selected-work" className="section container future-work"><div className="section-heading"><div><Eyebrow>01 — OUR PRODUCTS</Eyebrow><h2>Successful Delivered<br/><span className="text-muted">Products.</span></h2></div><Link to="/portfolio" className="text-link">See all products <Icon name="diagonal" size={19}/></Link></div><WorkShowcase/><p className="demo-caption">TAKE A LOOK AT OUR LATEST PRODUCTS.</p></section>
    <section className="future-services section"><div className="container"><div className="section-heading"><div><Eyebrow>02 — HOW WE HELP</Eyebrow><h2>What your business needs.<br/><span className="text-muted">All in one place.</span></h2></div><p>Websites, apps and software.<br/>Built to help your business grow.</p></div>
      <div className="service-bento">
        <Link to="/services/ui-ux-design" className="bento-card bento-design"><div className="bento-top"><span>01 / DESIGN</span><Icon name="diagonal" size={24}/></div><div className="design-playground" aria-hidden="true"><div className="design-cursor"><Icon name="diagonal" size={22}/> Make it exceptional.</div><div className="design-frame"><span className="frame-dot"/><span className="frame-dot"/><span className="frame-dot"/><span className="frame-dot"/><span className="design-type">Aa<span>.</span></span></div><div className="design-swatches"><i/><i/><i/><i/></div></div><div className="bento-copy"><h3>Looks good.<br/>Easy to use.</h3><p>Clear, simple designs that help your customers find what they need.</p><span>UI / UX · DESIGN SYSTEMS · PROTOTYPING</span></div></Link>
        <Link to="/services/web-development" className="bento-card bento-development"><div className="bento-top"><span>02 / DEVELOPMENT</span><Icon name="diagonal" size={24}/></div><div className="code-playground" aria-hidden="true"><div className="code-window"><div><i/><i/><i/><span>your-next-big-thing.tsx</span></div><pre><span>const</span> possibility = {'{'}<br/>  vision: <em>'Extraordinary'</em>,<br/>  experience: <em>'Seamless'</em>,<br/>  builtTo: <em>'Go further'</em><br/>{'}'};<br/><br/><span>return</span> &lt;<b>YourNextChapter</b> /&gt;</pre><div className="code-ready"><span/> Ready for what’s next <Icon name="check" size={15}/></div></div></div><div className="bento-copy"><h3>Fast websites.<br/>Built for your business.</h3><p>We build websites and online tools that work well as your business grows.</p><span>WEBSITES · WEB APPS · SAAS PLATFORMS</span></div></Link>
        <Link to="/services/app-development" className="bento-card bento-mobile"><div className="bento-top"><span>03 / MOBILE</span><Icon name="diagonal" size={24}/></div><div className="bento-copy"><h3>Your business.<br/>On their phone.</h3><p>Easy-to-use apps that keep your customers connected to your business.</p><span>IOS · ANDROID · CROSS-PLATFORM</span></div><div className="mini-phone" aria-hidden="true"><i/><div>9:41 <span>▰</span></div><span className="phone-greeting">YOUR NEXT CHAPTER</span><strong>Hello,<br/>possibility.</strong><div className="phone-orb">✳</div><div className="phone-action">Let’s go <span>↗</span></div></div></Link>
        <Link to="/services/automation" className="bento-card bento-automate"><div className="bento-top"><span>04 / CONNECT</span><Icon name="diagonal" size={24}/></div><div className="bento-copy"><h3>Save time.<br/>Get more done.</h3><p>Connect your tools and let software handle repeat tasks.</p><span>AUTOMATION · APIS · INTEGRATIONS</span></div><div className="connect-art" aria-hidden="true"><i/><i/><i/><span className="connect-core"><Icon name="nodes" size={30}/></span><span className="connect-node connect-node-one"><Icon name="cloud" size={20}/></span><span className="connect-node connect-node-two"><Icon name="bolt" size={20}/></span></div></Link>
      </div><div className="services-bottom"><p>Tell us what your business needs.</p><Link to="/services" className="text-link">See our services <Icon name="diagonal" size={18}/></Link></div>
    </div></section>
    <section className="section container future-partner"><div className="partner-art"><span className="partner-art-label">CONNECTED THINKING. SHARED AMBITION.</span><div className="partner-orbit"><i/><i/><i/><div className="partner-symbol">a<span>↗</span></div><span className="partner-dot"/></div><div className="partner-art-foot"><span>SMALL TEAM.</span><span>EXPANSIVE THINKING.</span></div></div><div className="partner-copy"><Eyebrow>03 — MEET YOUR TEAM</Eyebrow><h2>A team that cares.<br/><span className="text-muted">About your business.</span></h2><p>We design and build websites, apps and software. We listen to your needs, explain each step and keep you updated.</p><div className="partner-points"><div><Icon name="check" size={18}/><span>Talk directly with our team.</span></div><div><Icon name="check" size={18}/><span>Clear plans and regular updates.</span></div><div><Icon name="check" size={18}/><span>Support from start to launch and beyond.</span></div></div><Button to="/about" secondary>Meet our team</Button></div></section>
    <section className="future-process section"><div className="container"><div className="section-heading"><div><Eyebrow>04 — HOW WE WORK</Eyebrow><h2>From idea to launch.<br/><span className="text-muted">One step at a time.</span></h2></div><Link to="/process" className="text-link">See how we work <Icon name="diagonal" size={19}/></Link></div><div className="future-process-grid">{[['Discover','We learn about your business and make a clear plan.'],['Design','We create the design and improve it with your feedback.'],['Develop','We build your website or app and check that it works well.'],['Deliver','We help you go live and keep things running smoothly.']].map(([title, description], index) => <article key={title}><div><span>0{index+1}</span><Icon name="diagonal" size={20}/></div><h3>{title}<span>.</span></h3><p>{description}</p></article>)}</div></div></section>
    <CTA/>
  </>
}
